services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    env_file:
      - ./api/.env
    environment:
      - PYTHONPATH=/app
      - FLASK_APP=api.run
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    stdin_open: true
    tty: true
    depends_on:
      - api

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: idiotchess
      POSTGRES_USER: idiotuser
      POSTGRES_PASSWORD: secret
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
