"""Initial migration

Revision ID: 40a1d3b66ea9
Revises: 
Create Date: 2025-06-02 18:01:01.177299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '40a1d3b66ea9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_turn', sa.String(length=5), nullable=False),
    sa.Column('game_status', sa.String(length=50), nullable=False),
    sa.Column('white_player_type', sa.String(length=20), nullable=False),
    sa.Column('black_player_type', sa.String(length=20), nullable=False),
    sa.Column('white_player_name', sa.String(length=100), nullable=True),
    sa.Column('black_player_name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_table('board_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('move_number', sa.Integer(), nullable=False),
    sa.Column('board_state', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('captured_pieces', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['games.session_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('moves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('move_number', sa.Integer(), nullable=False),
    sa.Column('from_position', sa.ARRAY(sa.Integer()), nullable=False),
    sa.Column('to_position', sa.ARRAY(sa.Integer()), nullable=False),
    sa.Column('piece_type', sa.String(length=20), nullable=False),
    sa.Column('piece_color', sa.String(length=5), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['games.session_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('moves')
    op.drop_table('board_states')
    op.drop_table('games')
    # ### end Alembic commands ###
